import '../models/profile_model.dart';
import '../models/user_model.dart';
import '../models/mediator_model.dart';
import '../models/subscription_plan.dart';
import '../models/wallet_transaction.dart';
import '../models/notification_model.dart';
import '../models/chat_message.dart';

/// Centralized mock data service — replace with real API calls later
class MockDataService {
  // ── Mock Profiles ──────────────────────────────────────────────
  static List<ProfileModel> getMockProfiles() {
    return [
      ProfileModel(
        id: 'P001',
        userId: 'U001',
        name: 'Karthick',
        age: 27,
        gender: 'Male',
        height: "5'9\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Vanniyar',
        education: 'B.E.',
        occupation: 'Cloud Architect Engineer',
        employedIn: 'Private Sector',
        annualIncome: '10-15 Lakhs',
        city: 'Chennai',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_68.jpg',
        photos: [
          'assets/images/profiles/profile_68.jpg',
          'assets/images/profiles/profile_11.jpg',
          'assets/images/profiles/profile_12.jpg',
        ],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234567',
        profileCompletion: 90,
        star: 'Rohini',
        rasi: 'Taurus',
        aboutMe: 'I am a passionate software engineer who loves exploring new technologies. Looking for a like-minded partner.',
        diet: 'Non-Vegetarian',
        lastActive: DateTime.now().subtract(const Duration(hours: 2)),
      ),
      ProfileModel(
        id: 'P002',
        userId: 'U002',
        name: 'Srividhya',
        age: 25,
        gender: 'Female',
        height: "5'4\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Nadar',
        education: 'M.Sc.',
        occupation: 'Software Developer',
        employedIn: 'Private Sector',
        annualIncome: '8-10 Lakhs',
        city: 'Coimbatore',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_47.jpg',
        photos: [
          'assets/images/profiles/profile_47.jpg',
          'assets/images/profiles/profile_45.jpg',
        ],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234568',
        profileCompletion: 85,
        star: 'Punarpusam',
        rasi: 'Cancer',
        aboutMe: 'I love reading books and traveling. Looking for someone who shares similar interests.',
        lastActive: DateTime.now().subtract(const Duration(hours: 1)),
      ),
      ProfileModel(
        id: 'P003',
        userId: 'U003',
        name: 'Kishore K',
        age: 26,
        gender: 'Male',
        height: "5'7\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Nadar',
        education: 'MBA',
        occupation: 'Human Resource Professional',
        employedIn: 'Private Sector',
        annualIncome: '6-8 Lakhs',
        city: 'Madurai',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_59.jpg',
        photos: ['assets/images/profiles/profile_59.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234569',
        profileCompletion: 78,
        star: 'Bharani',
        rasi: 'Aries',
        aboutMe: 'HR Professional passionate about people management.',
        lastActive: DateTime.now().subtract(const Duration(minutes: 30)),
      ),
      ProfileModel(
        id: 'P004',
        userId: 'U004',
        name: 'Sathya',
        age: 27,
        gender: 'Male',
        height: "5'9\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Vanniyar',
        education: 'M.Com',
        occupation: 'Administrative Professional',
        employedIn: 'Government',
        annualIncome: '5-7 Lakhs',
        city: 'Coimbatore',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_53.jpg',
        photos: ['assets/images/profiles/profile_53.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: false,
        membershipId: 'M1234570',
        profileCompletion: 70,
        star: 'Ashwini',
        rasi: 'Aries',
        aboutMe: 'Government employee with a stable career. Looking for a loving partner.',
        lastActive: DateTime.now().subtract(const Duration(hours: 5)),
      ),
      ProfileModel(
        id: 'P005',
        userId: 'U005',
        name: 'Meera Desigan',
        age: 25,
        gender: 'Female',
        height: "5'6\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Gounder',
        education: 'B.E.',
        occupation: 'Mechanical Engineer',
        employedIn: 'Private Sector',
        annualIncome: '5-8 Lakhs',
        city: 'Chennai',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_44.jpg',
        photos: ['assets/images/profiles/profile_44.jpg'],
        isVerified: false,
        isPhotoVerified: false,
        isPremium: false,
        membershipId: 'M1234571',
        profileCompletion: 55,
        aboutMe: 'Mechanical engineer with a passion for innovation.',
        lastActive: DateTime.now().subtract(const Duration(hours: 3)),
      ),
      ProfileModel(
        id: 'P006',
        userId: 'U006',
        name: 'Lavanya',
        age: 24,
        gender: 'Female',
        height: "5'3\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Mudaliar',
        education: 'B.Sc.',
        occupation: 'Teacher',
        employedIn: 'Private Sector',
        annualIncome: '3-5 Lakhs',
        city: 'Trichy',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_32.jpg',
        photos: ['assets/images/profiles/profile_32.jpg'],
        isVerified: true,
        isPhotoVerified: false,
        isPremium: false,
        membershipId: 'M1234572',
        profileCompletion: 60,
        star: 'Punarpusam',
        rasi: 'Gemini',
        dob: '09/01/1993',
        birthTime: '09:10:00 AM',
        aboutMe: 'School teacher who loves arts and culture.',
        lastActive: DateTime.now().subtract(const Duration(days: 1)),
      ),
      ProfileModel(
        id: 'P007',
        userId: 'U007',
        name: 'Arjun R',
        age: 29,
        gender: 'Male',
        height: "5'10\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Pillai',
        education: 'M.Tech',
        occupation: 'Data Scientist',
        employedIn: 'Private Sector',
        annualIncome: '15-20 Lakhs',
        city: 'Bangalore',
        state: 'Karnataka',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_14.jpg',
        photos: ['assets/images/profiles/profile_14.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234573',
        profileCompletion: 95,
        star: 'Mrigashira',
        rasi: 'Taurus',
        aboutMe: 'Data scientist working at a top tech company. Love sports and fitness.',
        lastActive: DateTime.now().subtract(const Duration(minutes: 15)),
      ),
      ProfileModel(
        id: 'P008',
        userId: 'U008',
        name: 'Gayathri S',
        age: 23,
        gender: 'Female',
        height: "5'5\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Brahmin',
        education: 'B.Tech',
        occupation: 'UI/UX Designer',
        employedIn: 'Private Sector',
        annualIncome: '7-10 Lakhs',
        city: 'Chennai',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_25.jpg',
        photos: ['assets/images/profiles/profile_25.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: false,
        membershipId: 'M1234574',
        profileCompletion: 80,
        star: 'Revati',
        rasi: 'Pisces',
        aboutMe: 'Creative designer who loves to paint and travel.',
        lastActive: DateTime.now().subtract(const Duration(hours: 6)),
      ),
      ProfileModel(
        id: 'P009',
        userId: 'U009',
        name: 'Rahul M',
        age: 30,
        gender: 'Male',
        height: "5'11\"",
        maritalStatus: 'Divorced',
        religion: 'Hindu',
        caste: 'Thevar',
        education: 'MBA',
        occupation: 'Business Analyst',
        employedIn: 'Private Sector',
        annualIncome: '12-15 Lakhs',
        city: 'Hyderabad',
        state: 'Telangana',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_15.jpg',
        photos: ['assets/images/profiles/profile_15.jpg'],
        isVerified: true,
        isPhotoVerified: false,
        isPremium: true,
        membershipId: 'M1234575',
        profileCompletion: 72,
        aboutMe: 'Business analyst looking for a fresh start in life.',
        lastActive: DateTime.now().subtract(const Duration(days: 2)),
      ),
      ProfileModel(
        id: 'P010',
        userId: 'U010',
        name: 'Priya V',
        age: 26,
        gender: 'Female',
        height: "5'4\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Chettiar',
        education: 'CA',
        occupation: 'Chartered Accountant',
        employedIn: 'Private Sector',
        annualIncome: '10-15 Lakhs',
        city: 'Mumbai',
        state: 'Maharashtra',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_38.jpg',
        photos: ['assets/images/profiles/profile_38.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234576',
        profileCompletion: 88,
        star: 'Swati',
        rasi: 'Libra',
        aboutMe: 'CA who loves numbers and music.',
        lastActive: DateTime.now().subtract(const Duration(minutes: 45)),
      ),
      // ── 30 Indian Bride Profiles ───────────────────────────────
      ProfileModel(
        id: 'P011',
        userId: 'U011',
        name: 'Ananya Krishnamurthy',
        age: 24,
        gender: 'Female',
        height: "5'4\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Brahmin',
        subCaste: 'Iyer',
        motherTongue: 'Tamil',
        education: 'M.Tech',
        occupation: 'Software Engineer',
        employedIn: 'Private Sector',
        annualIncome: '8-10 Lakhs',
        city: 'Chennai',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_25.jpg',
        photos: ['assets/images/profiles/profile_25.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234577',
        profileCompletion: 92,
        star: 'Rohini',
        rasi: 'Taurus',
        dob: '15/03/2000',
        birthTime: '06:30:00 AM',
        birthPlace: 'Chennai',
        dosham: 'No',
        diet: 'Vegetarian',
        familyType: 'Nuclear',
        familyStatus: 'Upper Middle Class',
        fatherOccupation: 'Retired Bank Manager',
        motherOccupation: 'Homemaker',
        brothers: 1,
        sisters: 0,
        aboutMe: 'Software engineer passionate about technology and classical dance. Seeking a well-educated life partner.',
        partnerAgeRange: '26-32',
        partnerHeightRange: "5'6\" - 6'0\"",
        partnerEducation: 'Post Graduate',
        partnerOccupation: 'Any',
        partnerLocation: 'Tamil Nadu',
        lastActive: DateTime.now().subtract(const Duration(hours: 1)),
      ),
      ProfileModel(
        id: 'P012',
        userId: 'U012',
        name: 'Divya Subramaniam',
        age: 25,
        gender: 'Female',
        height: "5'5\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Gounder',
        subCaste: 'Vellalar',
        motherTongue: 'Tamil',
        education: 'MBBS',
        occupation: 'Doctor',
        employedIn: 'Government',
        annualIncome: '12-15 Lakhs',
        city: 'Coimbatore',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_32.jpg',
        photos: ['assets/images/profiles/profile_32.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234578',
        profileCompletion: 95,
        star: 'Karthigai',
        rasi: 'Aries',
        dob: '20/07/1999',
        birthTime: '10:15:00 AM',
        birthPlace: 'Coimbatore',
        dosham: 'No',
        diet: 'Vegetarian',
        familyType: 'Joint',
        familyStatus: 'Upper Middle Class',
        fatherOccupation: 'Business',
        motherOccupation: 'Teacher',
        brothers: 0,
        sisters: 1,
        aboutMe: 'Government doctor dedicated to healthcare. Love reading and yoga in my spare time.',
        partnerAgeRange: '27-33',
        partnerHeightRange: "5'7\" - 6'1\"",
        partnerEducation: 'Post Graduate',
        partnerOccupation: 'Any',
        partnerLocation: 'Tamil Nadu, Karnataka',
        lastActive: DateTime.now().subtract(const Duration(hours: 2)),
      ),
      ProfileModel(
        id: 'P013',
        userId: 'U013',
        name: 'Kalyani Natarajan',
        age: 23,
        gender: 'Female',
        height: "5'3\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Mudaliar',
        motherTongue: 'Tamil',
        education: 'B.E.',
        occupation: 'Civil Engineer',
        employedIn: 'Private Sector',
        annualIncome: '5-8 Lakhs',
        city: 'Salem',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_44.jpg',
        photos: ['assets/images/profiles/profile_44.jpg'],
        isVerified: true,
        isPhotoVerified: false,
        isPremium: false,
        membershipId: 'M1234579',
        profileCompletion: 75,
        star: 'Mirugashirisham',
        rasi: 'Gemini',
        diet: 'Non-Vegetarian',
        familyType: 'Nuclear',
        familyStatus: 'Middle Class',
        brothers: 1,
        sisters: 1,
        aboutMe: 'Civil engineer who loves trekking and photography. Looking for a genuine and supportive partner.',
        lastActive: DateTime.now().subtract(const Duration(hours: 5)),
      ),
      ProfileModel(
        id: 'P014',
        userId: 'U014',
        name: 'Nithya Selvaraj',
        age: 26,
        gender: 'Female',
        height: "5'6\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Nadar',
        motherTongue: 'Tamil',
        education: 'MBA',
        occupation: 'Marketing Manager',
        employedIn: 'Private Sector',
        annualIncome: '10-12 Lakhs',
        city: 'Chennai',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_45.jpg',
        photos: ['assets/images/profiles/profile_45.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234580',
        profileCompletion: 88,
        star: 'Thiruvadhirai',
        rasi: 'Gemini',
        dosham: 'No',
        diet: 'Non-Vegetarian',
        familyType: 'Nuclear',
        familyStatus: 'Upper Middle Class',
        fatherOccupation: 'Business',
        motherOccupation: 'Homemaker',
        brothers: 0,
        sisters: 0,
        aboutMe: 'Marketing professional who loves travelling and exploring new cuisines. Looking for a like-minded partner.',
        partnerAgeRange: '28-34',
        partnerHeightRange: "5'8\" - 6'0\"",
        lastActive: DateTime.now().subtract(const Duration(hours: 3)),
      ),
      ProfileModel(
        id: 'P015',
        userId: 'U015',
        name: 'Poorvika Chandran',
        age: 22,
        gender: 'Female',
        height: "5'4\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Vanniyar',
        motherTongue: 'Tamil',
        education: 'B.Sc. Computer Science',
        occupation: 'Data Analyst',
        employedIn: 'Private Sector',
        annualIncome: '4-6 Lakhs',
        city: 'Tiruppur',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_47.jpg',
        photos: ['assets/images/profiles/profile_47.jpg'],
        isVerified: false,
        isPhotoVerified: false,
        isPremium: false,
        membershipId: 'M1234581',
        profileCompletion: 60,
        star: 'Punarpusam',
        rasi: 'Cancer',
        diet: 'Vegetarian',
        familyType: 'Nuclear',
        familyStatus: 'Middle Class',
        brothers: 2,
        sisters: 0,
        aboutMe: 'Fresh data analyst excited about starting a new chapter of life.',
        lastActive: DateTime.now().subtract(const Duration(days: 1)),
      ),
      ProfileModel(
        id: 'P016',
        userId: 'U016',
        name: 'Ranjani Pillai',
        age: 27,
        gender: 'Female',
        height: "5'5\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Pillai',
        motherTongue: 'Tamil',
        education: 'M.Sc. Psychology',
        occupation: 'Clinical Psychologist',
        employedIn: 'Private Sector',
        annualIncome: '8-10 Lakhs',
        city: 'Bangalore',
        state: 'Karnataka',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_25.jpg',
        photos: ['assets/images/profiles/profile_25.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: false,
        membershipId: 'M1234582',
        profileCompletion: 82,
        star: 'Poosam',
        rasi: 'Cancer',
        diet: 'Vegetarian',
        familyType: 'Nuclear',
        familyStatus: 'Upper Middle Class',
        fatherOccupation: 'Engineer',
        motherOccupation: 'Teacher',
        brothers: 1,
        sisters: 0,
        aboutMe: 'Psychologist with a passion for mental wellness and Carnatic music. Looking for an understanding partner.',
        lastActive: DateTime.now().subtract(const Duration(hours: 4)),
      ),
      ProfileModel(
        id: 'P017',
        userId: 'U017',
        name: 'Shruthi Balakrishnan',
        age: 25,
        gender: 'Female',
        height: "5'3\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Brahmin',
        subCaste: 'Iyengar',
        motherTongue: 'Tamil',
        education: 'B.Com CA',
        occupation: 'Accountant',
        employedIn: 'Private Sector',
        annualIncome: '5-7 Lakhs',
        city: 'Trichy',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_32.jpg',
        photos: ['assets/images/profiles/profile_32.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: false,
        membershipId: 'M1234583',
        profileCompletion: 78,
        star: 'Ayilyam',
        rasi: 'Cancer',
        dosham: 'No',
        diet: 'Vegetarian',
        familyType: 'Joint',
        familyStatus: 'Middle Class',
        brothers: 0,
        sisters: 1,
        aboutMe: 'Accountant who values family traditions and loves cooking. Looking for a simple and caring partner.',
        lastActive: DateTime.now().subtract(const Duration(hours: 6)),
      ),
      ProfileModel(
        id: 'P018',
        userId: 'U018',
        name: 'Swetha Rajendran',
        age: 28,
        gender: 'Female',
        height: "5'6\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Thevar',
        motherTongue: 'Tamil',
        education: 'LLB',
        occupation: 'Lawyer',
        employedIn: 'Private Sector',
        annualIncome: '10-15 Lakhs',
        city: 'Madurai',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_38.jpg',
        photos: ['assets/images/profiles/profile_38.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234584',
        profileCompletion: 90,
        star: 'Magam',
        rasi: 'Leo',
        dosham: 'No',
        diet: 'Non-Vegetarian',
        familyType: 'Nuclear',
        familyStatus: 'Upper Middle Class',
        fatherOccupation: 'Retired Government Officer',
        motherOccupation: 'Homemaker',
        brothers: 1,
        sisters: 0,
        aboutMe: 'Advocate with 4 years of experience. Passionate about justice and social causes. Looking for an educated partner.',
        partnerAgeRange: '30-36',
        partnerHeightRange: "5'8\" - 6'2\"",
        lastActive: DateTime.now().subtract(const Duration(hours: 2)),
      ),
      ProfileModel(
        id: 'P019',
        userId: 'U019',
        name: 'Varshini Anand',
        age: 24,
        gender: 'Female',
        height: "5'4\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Chettiar',
        motherTongue: 'Tamil',
        education: 'B.Tech IT',
        occupation: 'Product Manager',
        employedIn: 'Private Sector',
        annualIncome: '12-15 Lakhs',
        city: 'Hyderabad',
        state: 'Telangana',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_44.jpg',
        photos: ['assets/images/profiles/profile_44.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234585',
        profileCompletion: 87,
        star: 'Pooram',
        rasi: 'Leo',
        dosham: 'No',
        diet: 'Non-Vegetarian',
        familyType: 'Nuclear',
        familyStatus: 'Upper Middle Class',
        brothers: 0,
        sisters: 1,
        aboutMe: 'Product manager in a leading tech firm. Love hiking, photography, and experimenting with new recipes.',
        partnerAgeRange: '26-32',
        partnerHeightRange: "5'7\" - 6'1\"",
        lastActive: DateTime.now().subtract(const Duration(minutes: 30)),
      ),
      ProfileModel(
        id: 'P020',
        userId: 'U020',
        name: 'Yamini Raghavan',
        age: 23,
        gender: 'Female',
        height: "5'2\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Brahmin',
        subCaste: 'Iyer',
        motherTongue: 'Tamil',
        education: 'B.A. Music',
        occupation: 'Music Teacher',
        employedIn: 'Private Sector',
        annualIncome: '3-5 Lakhs',
        city: 'Chennai',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_45.jpg',
        photos: ['assets/images/profiles/profile_45.jpg'],
        isVerified: true,
        isPhotoVerified: false,
        isPremium: false,
        membershipId: 'M1234586',
        profileCompletion: 70,
        star: 'Uthiram',
        rasi: 'Leo',
        dosham: 'No',
        diet: 'Vegetarian',
        familyType: 'Joint',
        familyStatus: 'Middle Class',
        fatherOccupation: 'Professor',
        motherOccupation: 'Homemaker',
        brothers: 0,
        sisters: 0,
        aboutMe: 'Carnatic vocalist and music teacher. Arts and classical music are my passion.',
        lastActive: DateTime.now().subtract(const Duration(days: 2)),
      ),
      ProfileModel(
        id: 'P021',
        userId: 'U021',
        name: 'Aishwarya Menon',
        age: 26,
        gender: 'Female',
        height: "5'5\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Nair',
        motherTongue: 'Malayalam',
        education: 'MBA Finance',
        occupation: 'Financial Analyst',
        employedIn: 'Private Sector',
        annualIncome: '10-15 Lakhs',
        city: 'Kochi',
        state: 'Kerala',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_47.jpg',
        photos: ['assets/images/profiles/profile_47.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234587',
        profileCompletion: 91,
        star: 'Hastham',
        rasi: 'Virgo',
        dosham: 'No',
        diet: 'Non-Vegetarian',
        familyType: 'Nuclear',
        familyStatus: 'Upper Middle Class',
        fatherOccupation: 'Doctor',
        motherOccupation: 'Nurse',
        brothers: 1,
        sisters: 0,
        aboutMe: 'Finance professional who loves Mohiniyattam dance and reading. Looking for a grounded and ambitious partner.',
        partnerAgeRange: '28-34',
        partnerHeightRange: "5'8\" - 6'0\"",
        lastActive: DateTime.now().subtract(const Duration(hours: 1)),
      ),
      ProfileModel(
        id: 'P022',
        userId: 'U022',
        name: 'Bhavana Iyer',
        age: 24,
        gender: 'Female',
        height: "5'4\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Brahmin',
        subCaste: 'Iyer',
        motherTongue: 'Tamil',
        education: 'M.Sc. Biotechnology',
        occupation: 'Research Scientist',
        employedIn: 'Private Sector',
        annualIncome: '6-8 Lakhs',
        city: 'Pune',
        state: 'Maharashtra',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_25.jpg',
        photos: ['assets/images/profiles/profile_25.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: false,
        membershipId: 'M1234588',
        profileCompletion: 80,
        star: 'Chithirai',
        rasi: 'Virgo',
        dosham: 'No',
        diet: 'Vegetarian',
        familyType: 'Nuclear',
        familyStatus: 'Middle Class',
        fatherOccupation: 'Software Engineer',
        motherOccupation: 'Teacher',
        brothers: 1,
        sisters: 0,
        aboutMe: 'Research scientist exploring life sciences. Passionate about environmental sustainability and music.',
        lastActive: DateTime.now().subtract(const Duration(hours: 8)),
      ),
      ProfileModel(
        id: 'P023',
        userId: 'U023',
        name: 'Chitra Devi',
        age: 27,
        gender: 'Female',
        height: "5'3\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Nadar',
        motherTongue: 'Tamil',
        education: 'B.Pharm',
        occupation: 'Pharmacist',
        employedIn: 'Government',
        annualIncome: '5-7 Lakhs',
        city: 'Tirunelveli',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_32.jpg',
        photos: ['assets/images/profiles/profile_32.jpg'],
        isVerified: true,
        isPhotoVerified: false,
        isPremium: false,
        membershipId: 'M1234589',
        profileCompletion: 68,
        star: 'Swathi',
        rasi: 'Libra',
        diet: 'Non-Vegetarian',
        familyType: 'Joint',
        familyStatus: 'Middle Class',
        brothers: 2,
        sisters: 1,
        aboutMe: 'Government pharmacist who values simplicity and family bonding. Enjoys cooking and gardening.',
        lastActive: DateTime.now().subtract(const Duration(days: 1)),
      ),
      ProfileModel(
        id: 'P024',
        userId: 'U024',
        name: 'Deepika Sundaram',
        age: 25,
        gender: 'Female',
        height: "5'6\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Gounder',
        motherTongue: 'Tamil',
        education: 'B.E. Electronics',
        occupation: 'VLSI Design Engineer',
        employedIn: 'Private Sector',
        annualIncome: '10-12 Lakhs',
        city: 'Bangalore',
        state: 'Karnataka',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_38.jpg',
        photos: ['assets/images/profiles/profile_38.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234590',
        profileCompletion: 86,
        star: 'Visakam',
        rasi: 'Libra',
        dosham: 'No',
        diet: 'Vegetarian',
        familyType: 'Nuclear',
        familyStatus: 'Upper Middle Class',
        fatherOccupation: 'Retired Teacher',
        motherOccupation: 'Homemaker',
        brothers: 0,
        sisters: 1,
        aboutMe: 'VLSI engineer working in semiconductor industry. Love badminton and classical songs.',
        partnerAgeRange: '27-33',
        partnerHeightRange: "5'8\" - 6'0\"",
        lastActive: DateTime.now().subtract(const Duration(hours: 3)),
      ),
      ProfileModel(
        id: 'P025',
        userId: 'U025',
        name: 'Ezhilarasi Pandian',
        age: 22,
        gender: 'Female',
        height: "5'2\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Thevar',
        motherTongue: 'Tamil',
        education: 'B.Sc. Nursing',
        occupation: 'Nurse',
        employedIn: 'Private Sector',
        annualIncome: '4-5 Lakhs',
        city: 'Madurai',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_44.jpg',
        photos: ['assets/images/profiles/profile_44.jpg'],
        isVerified: false,
        isPhotoVerified: false,
        isPremium: false,
        membershipId: 'M1234591',
        profileCompletion: 58,
        star: 'Anusham',
        rasi: 'Scorpio',
        diet: 'Non-Vegetarian',
        familyType: 'Joint',
        familyStatus: 'Middle Class',
        brothers: 1,
        sisters: 2,
        aboutMe: 'Dedicated nurse who believes in love, honesty, and mutual respect. Loves music and cooking.',
        lastActive: DateTime.now().subtract(const Duration(days: 2)),
      ),
      ProfileModel(
        id: 'P026',
        userId: 'U026',
        name: 'Gowsalya Murugan',
        age: 26,
        gender: 'Female',
        height: "5'4\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Vanniyar',
        motherTongue: 'Tamil',
        education: 'B.Ed.',
        occupation: 'School Teacher',
        employedIn: 'Government',
        annualIncome: '4-6 Lakhs',
        city: 'Villupuram',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_45.jpg',
        photos: ['assets/images/profiles/profile_45.jpg'],
        isVerified: true,
        isPhotoVerified: false,
        isPremium: false,
        membershipId: 'M1234592',
        profileCompletion: 65,
        star: 'Kettai',
        rasi: 'Scorpio',
        diet: 'Non-Vegetarian',
        familyType: 'Joint',
        familyStatus: 'Middle Class',
        fatherOccupation: 'Farmer',
        motherOccupation: 'Homemaker',
        brothers: 2,
        sisters: 0,
        aboutMe: 'Government school teacher passionate about education and children. Looking for a responsible and respectful partner.',
        lastActive: DateTime.now().subtract(const Duration(days: 1)),
      ),
      ProfileModel(
        id: 'P027',
        userId: 'U027',
        name: 'Harini Venkatesh',
        age: 29,
        gender: 'Female',
        height: "5'5\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Mudaliar',
        motherTongue: 'Tamil',
        education: 'M.Arch',
        occupation: 'Architect',
        employedIn: 'Private Sector',
        annualIncome: '10-12 Lakhs',
        city: 'Chennai',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_47.jpg',
        photos: ['assets/images/profiles/profile_47.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234593',
        profileCompletion: 89,
        star: 'Moolam',
        rasi: 'Sagittarius',
        dosham: 'No',
        diet: 'Non-Vegetarian',
        familyType: 'Nuclear',
        familyStatus: 'Upper Middle Class',
        fatherOccupation: 'Businessman',
        motherOccupation: 'Interior Designer',
        brothers: 0,
        sisters: 1,
        aboutMe: 'Architect with a flair for design and sustainability. Love art, travel, and cooking fusion food.',
        partnerAgeRange: '31-37',
        partnerHeightRange: "5'9\" - 6'1\"",
        lastActive: DateTime.now().subtract(const Duration(hours: 2)),
      ),
      ProfileModel(
        id: 'P028',
        userId: 'U028',
        name: 'Iswarya Balasubramaniam',
        age: 24,
        gender: 'Female',
        height: "5'4\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Brahmin',
        subCaste: 'Iyengar',
        motherTongue: 'Tamil',
        education: 'M.Com',
        occupation: 'Finance Executive',
        employedIn: 'Private Sector',
        annualIncome: '6-8 Lakhs',
        city: 'Trichy',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_25.jpg',
        photos: ['assets/images/profiles/profile_25.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: false,
        membershipId: 'M1234594',
        profileCompletion: 76,
        star: 'Purattathi',
        rasi: 'Aquarius',
        dosham: 'No',
        diet: 'Vegetarian',
        familyType: 'Joint',
        familyStatus: 'Middle Class',
        fatherOccupation: 'Retired Professor',
        motherOccupation: 'Homemaker',
        brothers: 1,
        sisters: 1,
        aboutMe: 'Finance executive who loves reading devotional books and classical dance. Looking for a cultured partner.',
        lastActive: DateTime.now().subtract(const Duration(hours: 10)),
      ),
      ProfileModel(
        id: 'P029',
        userId: 'U029',
        name: 'Janani Arumugam',
        age: 25,
        gender: 'Female',
        height: "5'5\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Nadar',
        motherTongue: 'Tamil',
        education: 'B.Tech CSE',
        occupation: 'Full Stack Developer',
        employedIn: 'Private Sector',
        annualIncome: '8-12 Lakhs',
        city: 'Chennai',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_32.jpg',
        photos: ['assets/images/profiles/profile_32.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234595',
        profileCompletion: 84,
        star: 'Revathi',
        rasi: 'Pisces',
        dosham: 'No',
        diet: 'Non-Vegetarian',
        familyType: 'Nuclear',
        familyStatus: 'Upper Middle Class',
        fatherOccupation: 'Engineer',
        motherOccupation: 'Doctor',
        brothers: 0,
        sisters: 0,
        aboutMe: 'Full stack developer at a product company. Enjoy trekking, origami, and binge-watching science documentaries.',
        partnerAgeRange: '27-33',
        partnerHeightRange: "5'7\" - 6'1\"",
        lastActive: DateTime.now().subtract(const Duration(hours: 1)),
      ),
      ProfileModel(
        id: 'P030',
        userId: 'U030',
        name: 'Kavitha Shanmugam',
        age: 28,
        gender: 'Female',
        height: "5'6\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Gounder',
        motherTongue: 'Tamil',
        education: 'M.D. Ayurveda',
        occupation: 'Ayurveda Practitioner',
        employedIn: 'Private Sector',
        annualIncome: '8-10 Lakhs',
        city: 'Erode',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_44.jpg',
        photos: ['assets/images/profiles/profile_44.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234596',
        profileCompletion: 88,
        star: 'Ashwini',
        rasi: 'Aries',
        dosham: 'No',
        diet: 'Vegetarian',
        familyType: 'Nuclear',
        familyStatus: 'Upper Middle Class',
        fatherOccupation: 'Farmer',
        motherOccupation: 'Nurse',
        brothers: 1,
        sisters: 0,
        aboutMe: 'Ayurveda doctor who believes in holistic wellness. Love nature, cooking, and folk music.',
        partnerAgeRange: '30-36',
        partnerHeightRange: "5'8\" - 6'0\"",
        lastActive: DateTime.now().subtract(const Duration(hours: 4)),
      ),
      ProfileModel(
        id: 'P031',
        userId: 'U031',
        name: 'Lalitha Kannan',
        age: 23,
        gender: 'Female',
        height: "5'3\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Brahmin',
        subCaste: 'Iyer',
        motherTongue: 'Tamil',
        education: 'B.A. English Literature',
        occupation: 'Content Writer',
        employedIn: 'Private Sector',
        annualIncome: '3-5 Lakhs',
        city: 'Coimbatore',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_45.jpg',
        photos: ['assets/images/profiles/profile_45.jpg'],
        isVerified: false,
        isPhotoVerified: false,
        isPremium: false,
        membershipId: 'M1234597',
        profileCompletion: 55,
        star: 'Bharani',
        rasi: 'Aries',
        diet: 'Vegetarian',
        familyType: 'Nuclear',
        familyStatus: 'Middle Class',
        brothers: 1,
        sisters: 1,
        aboutMe: 'Creative writer who loves books, poetry, and Bharatanatyam. Looking for an intellectual and kind partner.',
        lastActive: DateTime.now().subtract(const Duration(days: 3)),
      ),
      ProfileModel(
        id: 'P032',
        userId: 'U032',
        name: 'Madhumitha Sundar',
        age: 26,
        gender: 'Female',
        height: "5'5\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Pillai',
        motherTongue: 'Tamil',
        education: 'M.Tech Biomedical',
        occupation: 'Biomedical Engineer',
        employedIn: 'Private Sector',
        annualIncome: '8-10 Lakhs',
        city: 'Chennai',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_47.jpg',
        photos: ['assets/images/profiles/profile_47.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234598',
        profileCompletion: 85,
        star: 'Rohini',
        rasi: 'Taurus',
        dosham: 'No',
        diet: 'Non-Vegetarian',
        familyType: 'Nuclear',
        familyStatus: 'Upper Middle Class',
        fatherOccupation: 'IAS Officer',
        motherOccupation: 'Lawyer',
        brothers: 0,
        sisters: 1,
        aboutMe: 'Biomedical engineer at a healthcare startup. Avid reader and passionate about women\'s health.',
        partnerAgeRange: '28-34',
        partnerHeightRange: "5'8\" - 6'1\"",
        lastActive: DateTime.now().subtract(const Duration(hours: 2)),
      ),
      ProfileModel(
        id: 'P033',
        userId: 'U033',
        name: 'Nandhini Ravi',
        age: 24,
        gender: 'Female',
        height: "5'4\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Mudaliar',
        motherTongue: 'Tamil',
        education: 'BDS',
        occupation: 'Dentist',
        employedIn: 'Private Sector',
        annualIncome: '8-12 Lakhs',
        city: 'Vellore',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_25.jpg',
        photos: ['assets/images/profiles/profile_25.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: false,
        membershipId: 'M1234599',
        profileCompletion: 80,
        star: 'Krithigai',
        rasi: 'Taurus',
        dosham: 'No',
        diet: 'Non-Vegetarian',
        familyType: 'Nuclear',
        familyStatus: 'Upper Middle Class',
        fatherOccupation: 'Doctor',
        motherOccupation: 'Teacher',
        brothers: 0,
        sisters: 0,
        aboutMe: 'Dentist running her own clinic. Loves painting, cooking, and social work on weekends.',
        lastActive: DateTime.now().subtract(const Duration(hours: 6)),
      ),
      ProfileModel(
        id: 'P034',
        userId: 'U034',
        name: 'Oviya Murugesan',
        age: 22,
        gender: 'Female',
        height: "5'3\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Nadar',
        motherTongue: 'Tamil',
        education: 'B.Tech EEE',
        occupation: 'Electrical Engineer',
        employedIn: 'Private Sector',
        annualIncome: '4-6 Lakhs',
        city: 'Tirunelveli',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_32.jpg',
        photos: ['assets/images/profiles/profile_32.jpg'],
        isVerified: false,
        isPhotoVerified: false,
        isPremium: false,
        membershipId: 'M1234600',
        profileCompletion: 60,
        star: 'Mirugashirisham',
        rasi: 'Gemini',
        diet: 'Non-Vegetarian',
        familyType: 'Joint',
        familyStatus: 'Middle Class',
        brothers: 1,
        sisters: 1,
        aboutMe: 'Fresh electrical engineer with enthusiasm for renewable energy. Loves movies, drawing, and spending time with family.',
        lastActive: DateTime.now().subtract(const Duration(days: 2)),
      ),
      ProfileModel(
        id: 'P035',
        userId: 'U035',
        name: 'Pavithra Ganesan',
        age: 27,
        gender: 'Female',
        height: "5'5\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Brahmin',
        subCaste: 'Iyengar',
        motherTongue: 'Tamil',
        education: 'Ph.D. Chemistry',
        occupation: 'Research Scientist',
        employedIn: 'Government',
        annualIncome: '10-12 Lakhs',
        city: 'Chennai',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_38.jpg',
        photos: ['assets/images/profiles/profile_38.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234601',
        profileCompletion: 93,
        star: 'Thiruvadhirai',
        rasi: 'Gemini',
        dosham: 'No',
        diet: 'Vegetarian',
        familyType: 'Nuclear',
        familyStatus: 'Upper Middle Class',
        fatherOccupation: 'Professor',
        motherOccupation: 'Professor',
        brothers: 0,
        sisters: 0,
        aboutMe: 'PhD researcher passionate about materials science. Classical singer and avid reader.',
        partnerAgeRange: '29-35',
        partnerHeightRange: "5'8\" - 6'2\"",
        lastActive: DateTime.now().subtract(const Duration(hours: 3)),
      ),
      ProfileModel(
        id: 'P036',
        userId: 'U036',
        name: 'Revathi Somasundaram',
        age: 25,
        gender: 'Female',
        height: "5'4\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Chettiar',
        motherTongue: 'Tamil',
        education: 'B.Sc. Fashion Design',
        occupation: 'Fashion Designer',
        employedIn: 'Private Sector',
        annualIncome: '6-8 Lakhs',
        city: 'Chennai',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_44.jpg',
        photos: ['assets/images/profiles/profile_44.jpg'],
        isVerified: true,
        isPhotoVerified: false,
        isPremium: false,
        membershipId: 'M1234602',
        profileCompletion: 72,
        star: 'Punarpusam',
        rasi: 'Cancer',
        diet: 'Non-Vegetarian',
        familyType: 'Nuclear',
        familyStatus: 'Upper Middle Class',
        fatherOccupation: 'Businessman',
        motherOccupation: 'Homemaker',
        brothers: 1,
        sisters: 0,
        aboutMe: 'Fashion designer with my own label. Passionate about sustainable fashion, films, and travel.',
        lastActive: DateTime.now().subtract(const Duration(hours: 7)),
      ),
      ProfileModel(
        id: 'P037',
        userId: 'U037',
        name: 'Sangeetha Balamurugan',
        age: 28,
        gender: 'Female',
        height: "5'6\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Gounder',
        motherTongue: 'Tamil',
        education: 'M.Sc. Statistics',
        occupation: 'Data Scientist',
        employedIn: 'Private Sector',
        annualIncome: '15-20 Lakhs',
        city: 'Bangalore',
        state: 'Karnataka',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_45.jpg',
        photos: ['assets/images/profiles/profile_45.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234603',
        profileCompletion: 92,
        star: 'Poosam',
        rasi: 'Cancer',
        dosham: 'No',
        diet: 'Non-Vegetarian',
        familyType: 'Nuclear',
        familyStatus: 'Upper Middle Class',
        fatherOccupation: 'Engineer',
        motherOccupation: 'Doctor',
        brothers: 0,
        sisters: 1,
        aboutMe: 'Senior data scientist at a leading MNC. Passionate about AI ethics, hiking, and world cuisines.',
        partnerAgeRange: '30-36',
        partnerHeightRange: "5'9\" - 6'2\"",
        lastActive: DateTime.now().subtract(const Duration(hours: 1)),
      ),
      ProfileModel(
        id: 'P038',
        userId: 'U038',
        name: 'Thendral Vijay',
        age: 23,
        gender: 'Female',
        height: "5'3\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Vanniyar',
        motherTongue: 'Tamil',
        education: 'B.Sc. Agriculture',
        occupation: 'Agricultural Officer',
        employedIn: 'Government',
        annualIncome: '5-7 Lakhs',
        city: 'Pudukkottai',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_47.jpg',
        photos: ['assets/images/profiles/profile_47.jpg'],
        isVerified: true,
        isPhotoVerified: false,
        isPremium: false,
        membershipId: 'M1234604',
        profileCompletion: 65,
        star: 'Ayilyam',
        rasi: 'Cancer',
        diet: 'Non-Vegetarian',
        familyType: 'Joint',
        familyStatus: 'Middle Class',
        fatherOccupation: 'Farmer',
        motherOccupation: 'Homemaker',
        brothers: 2,
        sisters: 1,
        aboutMe: 'Government agricultural officer determined to help farmers. Love cooking traditional Tamil cuisine.',
        lastActive: DateTime.now().subtract(const Duration(days: 1)),
      ),
      ProfileModel(
        id: 'P039',
        userId: 'U039',
        name: 'Uma Devi Krishnan',
        age: 30,
        gender: 'Female',
        height: "5'5\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Brahmin',
        subCaste: 'Iyer',
        motherTongue: 'Tamil',
        education: 'MBA HR',
        occupation: 'HR Manager',
        employedIn: 'Private Sector',
        annualIncome: '12-15 Lakhs',
        city: 'Mumbai',
        state: 'Maharashtra',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_25.jpg',
        photos: ['assets/images/profiles/profile_25.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234605',
        profileCompletion: 90,
        star: 'Magam',
        rasi: 'Leo',
        dosham: 'No',
        diet: 'Vegetarian',
        familyType: 'Nuclear',
        familyStatus: 'Upper Middle Class',
        fatherOccupation: 'IPS Officer',
        motherOccupation: 'Teacher',
        brothers: 0,
        sisters: 1,
        aboutMe: 'HR manager with 7 years of experience. Loves yoga, devotional music, and reading philosophy.',
        partnerAgeRange: '32-38',
        partnerHeightRange: "5'8\" - 6'1\"",
        lastActive: DateTime.now().subtract(const Duration(hours: 2)),
      ),
      ProfileModel(
        id: 'P040',
        userId: 'U040',
        name: 'Vidhya Suresh',
        age: 24,
        gender: 'Female',
        height: "5'4\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Nadar',
        motherTongue: 'Tamil',
        education: 'B.Tech IT',
        occupation: 'Cloud Engineer',
        employedIn: 'Private Sector',
        annualIncome: '8-10 Lakhs',
        city: 'Chennai',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'assets/images/profiles/profile_32.jpg',
        photos: ['assets/images/profiles/profile_32.jpg'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234606',
        profileCompletion: 85,
        star: 'Rohini',
        rasi: 'Taurus',
        dosham: 'No',
        diet: 'Non-Vegetarian',
        familyType: 'Nuclear',
        familyStatus: 'Upper Middle Class',
        fatherOccupation: 'Engineer',
        motherOccupation: 'Nurse',
        brothers: 1,
        sisters: 0,
        aboutMe: 'Cloud engineer enthusiastic about DevOps and open-source. Loves trekking, photography, and Tamil poetry.',
        partnerAgeRange: '26-32',
        partnerHeightRange: "5'7\" - 6'0\"",
        lastActive: DateTime.now().subtract(const Duration(hours: 1)),
      ),
    ];
  }

  // ── Mock Users ─────────────────────────────────────────────────
  static List<UserModel> getMockUsers() {
    final profiles = getMockProfiles();
    return profiles.map((p) => UserModel(
      id: p.userId,
      name: p.name,
      email: '${p.name.toLowerCase().replaceAll(' ', '')}@gmail.com',
      phone: '+91 98765 ${43210 + int.parse(p.id.replaceAll(RegExp(r'[^0-9]'), ''))}',
      role: p.isPremium ? 'paid' : 'user',
      isVerified: p.isVerified,
      isPremium: p.isPremium,
      profileImage: p.profileImage,
    )).toList();
  }

  // ── Mock Mediators ─────────────────────────────────────────────
  static List<MediatorModel> getMockMediators() {
    return [
      MediatorModel(
        id: 'MED001',
        name: 'Rajesh Kumar',
        phone: '+91 99887 76654',
        email: 'rajesh.mediator@gmail.com',
        totalProfiles: 45,
        activeMatches: 12,
        commissionEarned: 25000,
        walletBalance: 8500,
      ),
      MediatorModel(
        id: 'MED002',
        name: 'Lakshmi Narayanan',
        phone: '+91 98765 54321',
        email: 'lakshmi.broker@gmail.com',
        totalProfiles: 32,
        activeMatches: 8,
        commissionEarned: 18500,
        walletBalance: 5200,
      ),
      MediatorModel(
        id: 'MED003',
        name: 'Suresh Babu',
        phone: '+91 91234 56789',
        email: 'suresh.mediator@gmail.com',
        totalProfiles: 67,
        activeMatches: 23,
        commissionEarned: 42000,
        walletBalance: 15000,
        isActive: false,
      ),
    ];
  }

  // ── Mock Subscription Plans ────────────────────────────────────
  static List<SubscriptionPlan> getMockPlans() {
    return [
      SubscriptionPlan(
        id: 'PLAN_M',
        name: 'Silver',
        duration: 'Monthly',
        price: 999,
        originalPrice: 1499,
        features: [
          'View up to 20 contacts',
          'Send 10 interests/day',
          'Chat with matches',
          'Basic search filters',
        ],
      ),
      SubscriptionPlan(
        id: 'PLAN_Q',
        name: 'Gold',
        duration: 'Quarterly',
        price: 2499,
        originalPrice: 3999,
        isPopular: true,
        features: [
          'View up to 75 contacts',
          'Send 30 interests/day',
          'Unlimited chat',
          'Advanced search filters',
          'Profile highlight',
          'View horoscope match',
        ],
      ),
      SubscriptionPlan(
        id: 'PLAN_Y',
        name: 'Diamond',
        duration: 'Yearly',
        price: 7999,
        originalPrice: 14999,
        features: [
          'Unlimited contact views',
          'Unlimited interests',
          'Unlimited chat',
          'All search filters',
          'Profile highlight & boost',
          'Horoscope matching',
          'Dedicated relationship manager',
          'Priority customer support',
        ],
      ),
    ];
  }

  // ── Mock Pay-Per-Profile Bundles ───────────────────────────────
  static List<ProfileUnlockBundle> getMockBundles() {
    return [
      ProfileUnlockBundle(id: 'BUN_1', profileCount: 1, price: 149),
      ProfileUnlockBundle(id: 'BUN_5', profileCount: 5, price: 599),
      ProfileUnlockBundle(id: 'BUN_10', profileCount: 10, price: 999),
    ];
  }

  // ── Mock Wallet Transactions ───────────────────────────────────
  static List<WalletTransaction> getMockTransactions() {
    return [
      WalletTransaction(
        id: 'TXN001',
        userId: 'MED001',
        type: 'credit',
        amount: 500,
        description: 'Commission for match M1234567',
        status: 'approved',
        date: DateTime.now().subtract(const Duration(days: 1)),
      ),
      WalletTransaction(
        id: 'TXN002',
        userId: 'MED001',
        type: 'credit',
        amount: 750,
        description: 'Commission for match M1234568',
        status: 'approved',
        date: DateTime.now().subtract(const Duration(days: 3)),
      ),
      WalletTransaction(
        id: 'TXN003',
        userId: 'MED001',
        type: 'withdrawal',
        amount: 2000,
        description: 'Withdrawal to bank account',
        status: 'pending',
        date: DateTime.now().subtract(const Duration(days: 5)),
      ),
      WalletTransaction(
        id: 'TXN004',
        userId: 'MED002',
        type: 'credit',
        amount: 350,
        description: 'Commission for match M1234570',
        status: 'approved',
        date: DateTime.now().subtract(const Duration(days: 2)),
      ),
      WalletTransaction(
        id: 'TXN005',
        userId: 'MED002',
        type: 'withdrawal',
        amount: 5000,
        description: 'Withdrawal to bank account',
        status: 'rejected',
        date: DateTime.now().subtract(const Duration(days: 7)),
      ),
    ];
  }

  // ── Mock Notifications ─────────────────────────────────────────
  static List<NotificationModel> getMockNotifications() {
    return [
      NotificationModel(
        id: 'N001',
        title: 'New Interest Received',
        body: 'Srividhya has expressed interest in your profile.',
        type: 'interest',
        createdAt: DateTime.now().subtract(const Duration(minutes: 30)),
      ),
      NotificationModel(
        id: 'N002',
        title: 'Profile Viewed',
        body: 'Kishore K viewed your profile.',
        type: 'system',
        createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      ),
      NotificationModel(
        id: 'N003',
        title: 'Match Found!',
        body: 'You and Gayathri S have a mutual match!',
        type: 'match',
        createdAt: DateTime.now().subtract(const Duration(hours: 5)),
      ),
      NotificationModel(
        id: 'N004',
        title: 'New Message',
        body: 'Srividhya sent you a message.',
        type: 'message',
        createdAt: DateTime.now().subtract(const Duration(hours: 8)),
      ),
      NotificationModel(
        id: 'N005',
        title: 'Profile Approved',
        body: 'Your profile has been verified and approved.',
        type: 'system',
        isRead: true,
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
      ),
      NotificationModel(
        id: 'N006',
        title: 'Premium Offer',
        body: 'Get 50% off on Diamond membership. Limited time!',
        type: 'system',
        isRead: true,
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
      ),
    ];
  }

  // ── Mock Chat Conversations ────────────────────────────────────
  static List<ChatConversation> getMockConversations() {
    return [
      ChatConversation(
        id: 'CONV001',
        recipientName: 'Srividhya',
        recipientImage: 'assets/images/profiles/profile_47.jpg',
        lastMessage: 'I like reading books too. Let us connect over a voice call.',
        lastMessageTime: DateTime.now().subtract(const Duration(minutes: 10)),
        unreadCount: 2,
        isOnline: true,
        isVerified: true,
        isPremium: true,
      ),
      ChatConversation(
        id: 'CONV002',
        recipientName: 'Gayathri S',
        recipientImage: 'assets/images/profiles/profile_25.jpg',
        lastMessage: 'That sounds great! When are you free?',
        lastMessageTime: DateTime.now().subtract(const Duration(hours: 3)),
        unreadCount: 0,
        isOnline: false,
        isVerified: true,
        isPremium: false,
      ),
      ChatConversation(
        id: 'CONV003',
        recipientName: 'Priya V',
        recipientImage: 'assets/images/profiles/profile_38.jpg',
        lastMessage: 'Hi, I saw your profile. Interested to know more.',
        lastMessageTime: DateTime.now().subtract(const Duration(days: 1)),
        unreadCount: 1,
        isOnline: false,
        isVerified: true,
        isPremium: true,
      ),
    ];
  }

  // ── Mock Chat Messages ─────────────────────────────────────────
  static List<ChatMessage> getMockMessages(String conversationId) {
    if (conversationId == 'CONV001') {
      return [
        ChatMessage(
          id: 'MSG001',
          senderId: 'U002',
          receiverId: 'U001',
          message: 'Hi !!\nI am interested in your profile.\nWould you like to communicate.\nI am leaving my father\'s contact no\n1234567890.\nLets hope for better future',
          timestamp: DateTime.now().subtract(const Duration(hours: 2, minutes: 30)),
          isSentByMe: false,
        ),
        ChatMessage(
          id: 'MSG002',
          senderId: 'U001',
          receiverId: 'U002',
          message: 'Hi, Thank you. I will see your profile...',
          timestamp: DateTime.now().subtract(const Duration(hours: 2, minutes: 28)),
          isSentByMe: true,
        ),
        ChatMessage(
          id: 'MSG003',
          senderId: 'U001',
          receiverId: 'U002',
          message: 'Meanwhile, Tell me about your interests and preferences...',
          timestamp: DateTime.now().subtract(const Duration(hours: 2, minutes: 25)),
          isSentByMe: true,
        ),
        ChatMessage(
          id: 'MSG004',
          senderId: 'U002',
          receiverId: 'U001',
          message: 'I am employed in Private Sector.\nResiding in Chennai. I love reading books.',
          timestamp: DateTime.now().subtract(const Duration(hours: 2, minutes: 20)),
          isSentByMe: false,
        ),
        ChatMessage(
          id: 'MSG005',
          senderId: 'U001',
          receiverId: 'U002',
          message: 'I like reading books too. Let us connect over a voice call if you would like to know more about me and my family.',
          timestamp: DateTime.now().subtract(const Duration(hours: 2, minutes: 15)),
          isSentByMe: true,
        ),
      ];
    }
    return [
      ChatMessage(
        id: 'MSG_DEF1',
        senderId: 'other',
        receiverId: 'U001',
        message: 'Hi, I saw your profile and I\'m interested.',
        timestamp: DateTime.now().subtract(const Duration(days: 1)),
        isSentByMe: false,
      ),
      ChatMessage(
        id: 'MSG_DEF2',
        senderId: 'U001',
        receiverId: 'other',
        message: 'Thank you! Tell me more about yourself.',
        timestamp: DateTime.now().subtract(const Duration(hours: 23)),
        isSentByMe: true,
      ),
    ];
  }

  // ── Success Stories (for home / marketing) ─────────────────────
  static List<Map<String, String>> getSuccessStories() {
    return [
      {'names': 'Abbas - Samira', 'image': 'assets/images/success_stories/couple_1.jpg'},
      {'names': 'Arjun - Gayathri', 'image': 'assets/images/success_stories/couple_2.jpg'},
      {'names': 'Rahul - Geetha', 'image': 'assets/images/success_stories/couple_3.jpg'},
      {'names': 'Mukesh - Nila', 'image': 'assets/images/success_stories/couple_4.jpg'},
      {'names': 'Manu - Priya', 'image': 'assets/images/success_stories/couple_5.jpg'},
      {'names': 'Sumesh - Meena', 'image': 'assets/images/success_stories/couple_6.jpg'},
      {'names': 'Siddarth - Aditi', 'image': 'assets/images/success_stories/couple_7.jpg'},
      {'names': 'Abishek - Aiswarya', 'image': 'assets/images/success_stories/couple_8.jpg'},
      {'names': 'Karthik - Kayal', 'image': 'assets/images/success_stories/couple_9.jpg'},
    ];
  }
}
