import '../models/profile_model.dart';
import '../models/user_model.dart';
import '../models/mediator_model.dart';
import '../models/subscription_plan.dart';
import '../models/wallet_transaction.dart';
import '../models/notification_model.dart';
import '../models/chat_message.dart';

/// Centralized mock data service — replace with real API calls later
class MockDataService {
  // ── Mock Profiles ──────────────────────────────────────────────
  static List<ProfileModel> getMockProfiles() {
    return [
      ProfileModel(
        id: 'P001',
        userId: 'U001',
        name: 'Karthick',
        age: 27,
        gender: 'Male',
        height: "5'9\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Vanniyar',
        education: 'B.E.',
        occupation: 'Cloud Architect Engineer',
        employedIn: 'Private Sector',
        annualIncome: '10-15 Lakhs',
        city: 'Chennai',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'https://i.pravatar.cc/300?img=68',
        photos: [
          'https://i.pravatar.cc/600?img=68',
          'https://i.pravatar.cc/600?img=11',
          'https://i.pravatar.cc/600?img=12',
        ],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234567',
        profileCompletion: 90,
        star: 'Rohini',
        rasi: 'Taurus',
        aboutMe: 'I am a passionate software engineer who loves exploring new technologies. Looking for a like-minded partner.',
        diet: 'Non-Vegetarian',
        lastActive: DateTime.now().subtract(const Duration(hours: 2)),
      ),
      ProfileModel(
        id: 'P002',
        userId: 'U002',
        name: 'Srividhya',
        age: 25,
        gender: 'Female',
        height: "5'4\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Nadar',
        education: 'M.Sc.',
        occupation: 'Software Developer',
        employedIn: 'Private Sector',
        annualIncome: '8-10 Lakhs',
        city: 'Coimbatore',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'https://i.pravatar.cc/300?img=47',
        photos: [
          'https://i.pravatar.cc/600?img=47',
          'https://i.pravatar.cc/600?img=45',
        ],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234568',
        profileCompletion: 85,
        star: 'Punarpusam',
        rasi: 'Cancer',
        aboutMe: 'I love reading books and traveling. Looking for someone who shares similar interests.',
        lastActive: DateTime.now().subtract(const Duration(hours: 1)),
      ),
      ProfileModel(
        id: 'P003',
        userId: 'U003',
        name: 'Kishore K',
        age: 26,
        gender: 'Male',
        height: "5'7\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Nadar',
        education: 'MBA',
        occupation: 'Human Resource Professional',
        employedIn: 'Private Sector',
        annualIncome: '6-8 Lakhs',
        city: 'Madurai',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'https://i.pravatar.cc/300?img=59',
        photos: ['https://i.pravatar.cc/600?img=59'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234569',
        profileCompletion: 78,
        star: 'Bharani',
        rasi: 'Aries',
        aboutMe: 'HR Professional passionate about people management.',
        lastActive: DateTime.now().subtract(const Duration(minutes: 30)),
      ),
      ProfileModel(
        id: 'P004',
        userId: 'U004',
        name: 'Sathya',
        age: 27,
        gender: 'Male',
        height: "5'9\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Vanniyar',
        education: 'M.Com',
        occupation: 'Administrative Professional',
        employedIn: 'Government',
        annualIncome: '5-7 Lakhs',
        city: 'Coimbatore',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'https://i.pravatar.cc/300?img=53',
        photos: ['https://i.pravatar.cc/600?img=53'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: false,
        membershipId: 'M1234570',
        profileCompletion: 70,
        star: 'Ashwini',
        rasi: 'Aries',
        aboutMe: 'Government employee with a stable career. Looking for a loving partner.',
        lastActive: DateTime.now().subtract(const Duration(hours: 5)),
      ),
      ProfileModel(
        id: 'P005',
        userId: 'U005',
        name: 'Meera Desigan',
        age: 25,
        gender: 'Female',
        height: "5'6\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Gounder',
        education: 'B.E.',
        occupation: 'Mechanical Engineer',
        employedIn: 'Private Sector',
        annualIncome: '5-8 Lakhs',
        city: 'Chennai',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'https://i.pravatar.cc/300?img=44',
        photos: ['https://i.pravatar.cc/600?img=44'],
        isVerified: false,
        isPhotoVerified: false,
        isPremium: false,
        membershipId: 'M1234571',
        profileCompletion: 55,
        aboutMe: 'Mechanical engineer with a passion for innovation.',
        lastActive: DateTime.now().subtract(const Duration(hours: 3)),
      ),
      ProfileModel(
        id: 'P006',
        userId: 'U006',
        name: 'Lavanya',
        age: 24,
        gender: 'Female',
        height: "5'3\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Mudaliar',
        education: 'B.Sc.',
        occupation: 'Teacher',
        employedIn: 'Private Sector',
        annualIncome: '3-5 Lakhs',
        city: 'Trichy',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'https://i.pravatar.cc/300?img=32',
        photos: ['https://i.pravatar.cc/600?img=32'],
        isVerified: true,
        isPhotoVerified: false,
        isPremium: false,
        membershipId: 'M1234572',
        profileCompletion: 60,
        star: 'Punarpusam',
        rasi: 'Gemini',
        dob: '09/01/1993',
        birthTime: '09:10:00 AM',
        aboutMe: 'School teacher who loves arts and culture.',
        lastActive: DateTime.now().subtract(const Duration(days: 1)),
      ),
      ProfileModel(
        id: 'P007',
        userId: 'U007',
        name: 'Arjun R',
        age: 29,
        gender: 'Male',
        height: "5'10\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Pillai',
        education: 'M.Tech',
        occupation: 'Data Scientist',
        employedIn: 'Private Sector',
        annualIncome: '15-20 Lakhs',
        city: 'Bangalore',
        state: 'Karnataka',
        country: 'India',
        profileImage: 'https://i.pravatar.cc/300?img=14',
        photos: ['https://i.pravatar.cc/600?img=14'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234573',
        profileCompletion: 95,
        star: 'Mrigashira',
        rasi: 'Taurus',
        aboutMe: 'Data scientist working at a top tech company. Love sports and fitness.',
        lastActive: DateTime.now().subtract(const Duration(minutes: 15)),
      ),
      ProfileModel(
        id: 'P008',
        userId: 'U008',
        name: 'Gayathri S',
        age: 23,
        gender: 'Female',
        height: "5'5\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Brahmin',
        education: 'B.Tech',
        occupation: 'UI/UX Designer',
        employedIn: 'Private Sector',
        annualIncome: '7-10 Lakhs',
        city: 'Chennai',
        state: 'Tamil Nadu',
        country: 'India',
        profileImage: 'https://i.pravatar.cc/300?img=25',
        photos: ['https://i.pravatar.cc/600?img=25'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: false,
        membershipId: 'M1234574',
        profileCompletion: 80,
        star: 'Revati',
        rasi: 'Pisces',
        aboutMe: 'Creative designer who loves to paint and travel.',
        lastActive: DateTime.now().subtract(const Duration(hours: 6)),
      ),
      ProfileModel(
        id: 'P009',
        userId: 'U009',
        name: 'Rahul M',
        age: 30,
        gender: 'Male',
        height: "5'11\"",
        maritalStatus: 'Divorced',
        religion: 'Hindu',
        caste: 'Thevar',
        education: 'MBA',
        occupation: 'Business Analyst',
        employedIn: 'Private Sector',
        annualIncome: '12-15 Lakhs',
        city: 'Hyderabad',
        state: 'Telangana',
        country: 'India',
        profileImage: 'https://i.pravatar.cc/300?img=15',
        photos: ['https://i.pravatar.cc/600?img=15'],
        isVerified: true,
        isPhotoVerified: false,
        isPremium: true,
        membershipId: 'M1234575',
        profileCompletion: 72,
        aboutMe: 'Business analyst looking for a fresh start in life.',
        lastActive: DateTime.now().subtract(const Duration(days: 2)),
      ),
      ProfileModel(
        id: 'P010',
        userId: 'U010',
        name: 'Priya V',
        age: 26,
        gender: 'Female',
        height: "5'4\"",
        maritalStatus: 'Never Married',
        religion: 'Hindu',
        caste: 'Chettiar',
        education: 'CA',
        occupation: 'Chartered Accountant',
        employedIn: 'Private Sector',
        annualIncome: '10-15 Lakhs',
        city: 'Mumbai',
        state: 'Maharashtra',
        country: 'India',
        profileImage: 'https://i.pravatar.cc/300?img=38',
        photos: ['https://i.pravatar.cc/600?img=38'],
        isVerified: true,
        isPhotoVerified: true,
        isPremium: true,
        membershipId: 'M1234576',
        profileCompletion: 88,
        star: 'Swati',
        rasi: 'Libra',
        aboutMe: 'CA who loves numbers and music.',
        lastActive: DateTime.now().subtract(const Duration(minutes: 45)),
      ),
    ];
  }

  // ── Mock Users ─────────────────────────────────────────────────
  static List<UserModel> getMockUsers() {
    final profiles = getMockProfiles();
    return profiles.map((p) => UserModel(
      id: p.userId,
      name: p.name,
      email: '${p.name.toLowerCase().replaceAll(' ', '')}@gmail.com',
      phone: '+91 98765 ${43210 + int.parse(p.id.replaceAll(RegExp(r'[^0-9]'), ''))}',
      role: p.isPremium ? 'paid' : 'user',
      isVerified: p.isVerified,
      isPremium: p.isPremium,
      profileImage: p.profileImage,
    )).toList();
  }

  // ── Mock Mediators ─────────────────────────────────────────────
  static List<MediatorModel> getMockMediators() {
    return [
      MediatorModel(
        id: 'MED001',
        name: 'Rajesh Kumar',
        phone: '+91 99887 76654',
        email: 'rajesh.mediator@gmail.com',
        totalProfiles: 45,
        activeMatches: 12,
        commissionEarned: 25000,
        walletBalance: 8500,
      ),
      MediatorModel(
        id: 'MED002',
        name: 'Lakshmi Narayanan',
        phone: '+91 98765 54321',
        email: 'lakshmi.broker@gmail.com',
        totalProfiles: 32,
        activeMatches: 8,
        commissionEarned: 18500,
        walletBalance: 5200,
      ),
      MediatorModel(
        id: 'MED003',
        name: 'Suresh Babu',
        phone: '+91 91234 56789',
        email: 'suresh.mediator@gmail.com',
        totalProfiles: 67,
        activeMatches: 23,
        commissionEarned: 42000,
        walletBalance: 15000,
        isActive: false,
      ),
    ];
  }

  // ── Mock Subscription Plans ────────────────────────────────────
  static List<SubscriptionPlan> getMockPlans() {
    return [
      SubscriptionPlan(
        id: 'PLAN_M',
        name: 'Silver',
        duration: 'Monthly',
        price: 999,
        originalPrice: 1499,
        features: [
          'View up to 20 contacts',
          'Send 10 interests/day',
          'Chat with matches',
          'Basic search filters',
        ],
      ),
      SubscriptionPlan(
        id: 'PLAN_Q',
        name: 'Gold',
        duration: 'Quarterly',
        price: 2499,
        originalPrice: 3999,
        isPopular: true,
        features: [
          'View up to 75 contacts',
          'Send 30 interests/day',
          'Unlimited chat',
          'Advanced search filters',
          'Profile highlight',
          'View horoscope match',
        ],
      ),
      SubscriptionPlan(
        id: 'PLAN_Y',
        name: 'Diamond',
        duration: 'Yearly',
        price: 7999,
        originalPrice: 14999,
        features: [
          'Unlimited contact views',
          'Unlimited interests',
          'Unlimited chat',
          'All search filters',
          'Profile highlight & boost',
          'Horoscope matching',
          'Dedicated relationship manager',
          'Priority customer support',
        ],
      ),
    ];
  }

  // ── Mock Pay-Per-Profile Bundles ───────────────────────────────
  static List<ProfileUnlockBundle> getMockBundles() {
    return [
      ProfileUnlockBundle(id: 'BUN_1', profileCount: 1, price: 149),
      ProfileUnlockBundle(id: 'BUN_5', profileCount: 5, price: 599),
      ProfileUnlockBundle(id: 'BUN_10', profileCount: 10, price: 999),
    ];
  }

  // ── Mock Wallet Transactions ───────────────────────────────────
  static List<WalletTransaction> getMockTransactions() {
    return [
      WalletTransaction(
        id: 'TXN001',
        userId: 'MED001',
        type: 'credit',
        amount: 500,
        description: 'Commission for match M1234567',
        status: 'approved',
        date: DateTime.now().subtract(const Duration(days: 1)),
      ),
      WalletTransaction(
        id: 'TXN002',
        userId: 'MED001',
        type: 'credit',
        amount: 750,
        description: 'Commission for match M1234568',
        status: 'approved',
        date: DateTime.now().subtract(const Duration(days: 3)),
      ),
      WalletTransaction(
        id: 'TXN003',
        userId: 'MED001',
        type: 'withdrawal',
        amount: 2000,
        description: 'Withdrawal to bank account',
        status: 'pending',
        date: DateTime.now().subtract(const Duration(days: 5)),
      ),
      WalletTransaction(
        id: 'TXN004',
        userId: 'MED002',
        type: 'credit',
        amount: 350,
        description: 'Commission for match M1234570',
        status: 'approved',
        date: DateTime.now().subtract(const Duration(days: 2)),
      ),
      WalletTransaction(
        id: 'TXN005',
        userId: 'MED002',
        type: 'withdrawal',
        amount: 5000,
        description: 'Withdrawal to bank account',
        status: 'rejected',
        date: DateTime.now().subtract(const Duration(days: 7)),
      ),
    ];
  }

  // ── Mock Notifications ─────────────────────────────────────────
  static List<NotificationModel> getMockNotifications() {
    return [
      NotificationModel(
        id: 'N001',
        title: 'New Interest Received',
        body: 'Srividhya has expressed interest in your profile.',
        type: 'interest',
        createdAt: DateTime.now().subtract(const Duration(minutes: 30)),
      ),
      NotificationModel(
        id: 'N002',
        title: 'Profile Viewed',
        body: 'Kishore K viewed your profile.',
        type: 'system',
        createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      ),
      NotificationModel(
        id: 'N003',
        title: 'Match Found!',
        body: 'You and Gayathri S have a mutual match!',
        type: 'match',
        createdAt: DateTime.now().subtract(const Duration(hours: 5)),
      ),
      NotificationModel(
        id: 'N004',
        title: 'New Message',
        body: 'Srividhya sent you a message.',
        type: 'message',
        createdAt: DateTime.now().subtract(const Duration(hours: 8)),
      ),
      NotificationModel(
        id: 'N005',
        title: 'Profile Approved',
        body: 'Your profile has been verified and approved.',
        type: 'system',
        isRead: true,
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
      ),
      NotificationModel(
        id: 'N006',
        title: 'Premium Offer',
        body: 'Get 50% off on Diamond membership. Limited time!',
        type: 'system',
        isRead: true,
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
      ),
    ];
  }

  // ── Mock Chat Conversations ────────────────────────────────────
  static List<ChatConversation> getMockConversations() {
    return [
      ChatConversation(
        id: 'CONV001',
        recipientName: 'Srividhya',
        recipientImage: 'https://i.pravatar.cc/150?img=47',
        lastMessage: 'I like reading books too. Let us connect over a voice call.',
        lastMessageTime: DateTime.now().subtract(const Duration(minutes: 10)),
        unreadCount: 2,
        isOnline: true,
        isVerified: true,
        isPremium: true,
      ),
      ChatConversation(
        id: 'CONV002',
        recipientName: 'Gayathri S',
        recipientImage: 'https://i.pravatar.cc/150?img=25',
        lastMessage: 'That sounds great! When are you free?',
        lastMessageTime: DateTime.now().subtract(const Duration(hours: 3)),
        unreadCount: 0,
        isOnline: false,
        isVerified: true,
        isPremium: false,
      ),
      ChatConversation(
        id: 'CONV003',
        recipientName: 'Priya V',
        recipientImage: 'https://i.pravatar.cc/150?img=38',
        lastMessage: 'Hi, I saw your profile. Interested to know more.',
        lastMessageTime: DateTime.now().subtract(const Duration(days: 1)),
        unreadCount: 1,
        isOnline: false,
        isVerified: true,
        isPremium: true,
      ),
    ];
  }

  // ── Mock Chat Messages ─────────────────────────────────────────
  static List<ChatMessage> getMockMessages(String conversationId) {
    if (conversationId == 'CONV001') {
      return [
        ChatMessage(
          id: 'MSG001',
          senderId: 'U002',
          receiverId: 'U001',
          message: 'Hi !!\nI am interested in your profile.\nWould you like to communicate.\nI am leaving my father\'s contact no\n1234567890.\nLets hope for better future',
          timestamp: DateTime.now().subtract(const Duration(hours: 2, minutes: 30)),
          isSentByMe: false,
        ),
        ChatMessage(
          id: 'MSG002',
          senderId: 'U001',
          receiverId: 'U002',
          message: 'Hi, Thank you. I will see your profile...',
          timestamp: DateTime.now().subtract(const Duration(hours: 2, minutes: 28)),
          isSentByMe: true,
        ),
        ChatMessage(
          id: 'MSG003',
          senderId: 'U001',
          receiverId: 'U002',
          message: 'Meanwhile, Tell me about your interests and preferences...',
          timestamp: DateTime.now().subtract(const Duration(hours: 2, minutes: 25)),
          isSentByMe: true,
        ),
        ChatMessage(
          id: 'MSG004',
          senderId: 'U002',
          receiverId: 'U001',
          message: 'I am employed in Private Sector.\nResiding in Chennai. I love reading books.',
          timestamp: DateTime.now().subtract(const Duration(hours: 2, minutes: 20)),
          isSentByMe: false,
        ),
        ChatMessage(
          id: 'MSG005',
          senderId: 'U001',
          receiverId: 'U002',
          message: 'I like reading books too. Let us connect over a voice call if you would like to know more about me and my family.',
          timestamp: DateTime.now().subtract(const Duration(hours: 2, minutes: 15)),
          isSentByMe: true,
        ),
      ];
    }
    return [
      ChatMessage(
        id: 'MSG_DEF1',
        senderId: 'other',
        receiverId: 'U001',
        message: 'Hi, I saw your profile and I\'m interested.',
        timestamp: DateTime.now().subtract(const Duration(days: 1)),
        isSentByMe: false,
      ),
      ChatMessage(
        id: 'MSG_DEF2',
        senderId: 'U001',
        receiverId: 'other',
        message: 'Thank you! Tell me more about yourself.',
        timestamp: DateTime.now().subtract(const Duration(hours: 23)),
        isSentByMe: true,
      ),
    ];
  }

  // ── Success Stories (for home / marketing) ─────────────────────
  static List<Map<String, String>> getSuccessStories() {
    return [
      {'names': 'Abbas - Samira', 'image': 'https://i.pravatar.cc/300?img=1'},
      {'names': 'Arjun - Gayathri', 'image': 'https://i.pravatar.cc/300?img=2'},
      {'names': 'Rahul - Geetha', 'image': 'https://i.pravatar.cc/300?img=3'},
      {'names': 'Mukesh - Nila', 'image': 'https://i.pravatar.cc/300?img=4'},
      {'names': 'Manu - Priya', 'image': 'https://i.pravatar.cc/300?img=5'},
      {'names': 'Sumesh - Meena', 'image': 'https://i.pravatar.cc/300?img=6'},
      {'names': 'Siddarth - Aditi', 'image': 'https://i.pravatar.cc/300?img=7'},
      {'names': 'Abishek - Aiswarya', 'image': 'https://i.pravatar.cc/300?img=8'},
      {'names': 'Karthik - Kayal', 'image': 'https://i.pravatar.cc/300?img=9'},
    ];
  }
}
